# Back base container for not having to pip install every time
FROM python:3.10.6-buster

RUN apt-get update && apt-get install -y libhdf5-dev

WORKDIR /prod
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONPATH="${PYTHONPATH}:/prod"
